// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-jobs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/shared.ts
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Connect with your Intervixa AI account." }],
    isError: true
  };
}
function dbError(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function rows(data) {
  const items = data ?? [];
  return {
    content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
    structuredContent: { count: items.length, items }
  };
}

// src/lib/mcp/tools/search-jobs.ts
var search_jobs_default = defineTool({
  name: "search_jobs",
  title: "Search jobs",
  description: "Search the latest Cloud/DevOps job listings collected by Intervixa AI.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free text matched against job title."),
    company: z.string().trim().optional().describe("Filter by company name."),
    location: z.string().trim().optional().describe("Filter by location."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, company, location, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("jobs").select("id,title,company_name,location,skills_required,apply_link,source,posted_at,description").order("posted_at", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (query) q = q.ilike("title", `%${query}%`);
    if (company) q = q.ilike("company_name", `%${company}%`);
    if (location) q = q.ilike("location", `%${location}%`);
    const { data, error } = await q;
    return error ? dbError(error.message) : rows(data);
  }
});

// src/lib/mcp/tools/search-interview-questions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var search_interview_questions_default = defineTool2({
  name: "search_interview_questions",
  title: "Search interview questions",
  description: "Search topic-wise interview questions with answers, hints and explanations.",
  inputSchema: {
    topic: z2.string().trim().optional().describe("Topic, e.g. Linux, AWS, Docker, Kubernetes."),
    role: z2.string().trim().optional().describe("Target role, e.g. DevOps Engineer."),
    company: z2.string().trim().optional().describe("Company the question was asked at."),
    difficulty: z2.string().trim().optional().describe("Difficulty, e.g. easy, medium, hard."),
    query: z2.string().trim().optional().describe("Free text matched against the question."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ topic, role, company, difficulty, query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("interview_questions").select("id,role,topic,company,difficulty,tags,question,hint,answer,explanation").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (topic) q = q.ilike("topic", `%${topic}%`);
    if (role) q = q.ilike("role", `%${role}%`);
    if (company) q = q.ilike("company", `%${company}%`);
    if (difficulty) q = q.ilike("difficulty", `%${difficulty}%`);
    if (query) q = q.ilike("question", `%${query}%`);
    const { data, error } = await q;
    return error ? dbError(error.message) : rows(data);
  }
});

// src/lib/mcp/tools/search-company-questions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var search_company_questions_default = defineTool3({
  name: "search_company_questions",
  title: "Search company-wise questions",
  description: "Search interview questions grouped by company, role and required skills.",
  inputSchema: {
    company: z3.string().trim().optional().describe("Company name."),
    role: z3.string().trim().optional().describe("Role, e.g. Cloud Engineer."),
    query: z3.string().trim().optional().describe("Free text matched against the question."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company, role, query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("company_questions").select("id,company,role,location,skills,question,answer,difficulty,document_link").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (company) q = q.ilike("company", `%${company}%`);
    if (role) q = q.ilike("role", `%${role}%`);
    if (query) q = q.ilike("question", `%${query}%`);
    const { data, error } = await q;
    return error ? dbError(error.message) : rows(data);
  }
});

// src/lib/mcp/tools/search-scenario-questions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var search_scenario_questions_default = defineTool4({
  name: "search_scenario_questions",
  title: "Search scenario questions",
  description: "Search real-world scenario-based Cloud/DevOps interview questions.",
  inputSchema: {
    technology: z4.string().trim().optional().describe("Technology, e.g. Kubernetes, Terraform."),
    query: z4.string().trim().optional().describe("Free text matched against the scenario title."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ technology, query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("scenario_questions").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (technology) q = q.ilike("technology", `%${technology}%`);
    if (query) q = q.ilike("title", `%${query}%`);
    const { data, error } = await q;
    return error ? dbError(error.message) : rows(data);
  }
});

// src/lib/mcp/tools/search-hr-contacts.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var search_hr_contacts_default = defineTool5({
  name: "search_hr_contacts",
  title: "Search HR contacts",
  description: "Search recruiter/HR contacts collected from recent Cloud & DevOps hiring posts.",
  inputSchema: {
    company: z5.string().trim().optional().describe("Company name."),
    query: z5.string().trim().optional().describe("Free text matched against the contact name."),
    limit: z5.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company, query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("hr_contacts").select("id,name,company,email,linkedin,role_focus,source_url,notes,posted_at").order("posted_at", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (company) q = q.ilike("company", `%${company}%`);
    if (query) q = q.ilike("name", `%${query}%`);
    const { data, error } = await q;
    return error ? dbError(error.message) : rows(data);
  }
});

// src/lib/mcp/tools/get-prep-roadmap.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_prep_roadmap_default = defineTool6({
  name: "get_prep_roadmap",
  title: "Get prep roadmap",
  description: "Get the ordered Cloud & DevOps interview preparation roadmap modules and their topics.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("roadmap_modules").select("id,title,difficulty,duration,topics,order_index,progress").order("order_index", { ascending: true });
    return error ? dbError(error.message) : rows(data);
  }
});

// src/lib/mcp/tools/list-cold-email-templates.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_cold_email_templates_default = defineTool7({
  name: "list_cold_email_templates",
  title: "List cold email templates",
  description: "List the cold email / outreach templates available in Intervixa AI.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("cold_email_templates").select("id,template_name,email_subject,email_body").order("created_at", { ascending: true });
    return error ? dbError(error.message) : rows(data);
  }
});

// src/lib/mcp/tools/list-resume-templates.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_resume_templates_default = defineTool8({
  name: "list_resume_templates",
  title: "List resume templates",
  description: "List downloadable ATS resume sample templates.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("resume_templates").select("id,name,file_url,created_at").order("created_at", { ascending: false });
    return error ? dbError(error.message) : rows(data);
  }
});

// src/lib/mcp/index.ts
var projectRef = "sbxomojhljyonzkleoiv";
var mcp_default = defineMcp({
  name: "intervix-ai",
  title: "Intervix_Ai",
  version: "0.1.0",
  instructions: "Tools for Intervixa AI, a Cloud & DevOps interview preparation platform. Use search_jobs for the latest job listings, search_interview_questions and search_company_questions for interview prep, search_scenario_questions for real-world scenarios, get_prep_roadmap for a study plan, search_hr_contacts for recruiter outreach, and the template tools for cold emails and ATS resume samples.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_jobs_default,
    search_interview_questions_default,
    search_company_questions_default,
    search_scenario_questions_default,
    search_hr_contacts_default,
    get_prep_roadmap_default,
    list_cold_email_templates_default,
    list_resume_templates_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
